development:
  sessions:
    default:
      database: mongoid_cancan_bug_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        safe: false
  options:
    allow_dynamic_fields: false
    identity_map_enabled: false
    include_root_in_json: false
    include_type_for_serialization: false
    preload_models: false
    protect_sensitive_fields: true
    raise_not_found_error: true
    scope_overwrite_exception: false
    skip_version_check: false
    use_activesupport_time_zone: true
    use_utc: true
test:
  sessions:
    default:
      database: mongoid_cancan_bug_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    identity_map_enabled: true
